#!/bin/bash

file_list=$1
shift

nsplit=4
bias_archive_dir=${REDUX_BASE_DIR}/bias_bank
cleanup=yes

while [ $# -gt 0 ] ; do eval $1 ; shift ; done

[ -d "$bias_archive_dir" ] || mkdir $bias_archive_dir

[ -f $file_list ] || { echo "No file $file_list" ; exit 1 ; }

go_iter=0
function gonogo() {
    ((go_iter++))
    [ "$((go_iter%NBATCH))" -eq 0 ] && wait
}

dte=`date -u +20%y%m%d_%H%M%S`
file0=`head -1 $file_list`
dte1=`basename $file0 | sed -e 's/f//g' -e 's/C/ /g' | awk '{print $1}'`
me=`basename $0`
here=`pwd`
workdir=${here}/${me}_${dte}_$$
[ -d $workdir ] || mkdir $workdir

echo "Working in directory $workdir, logging to ${workdir}/${me}_${dte}_$$.log"
exec > ${workdir}/${me}_${dte}_$$.log 2>&1

for file in `cat $file_list`; do
    bfile=`basename $file`
    extension=${bfile##*.}
    bfile0=${bfile%'.bz2'}
    bfile0=${bfile0%'.fz'}
    if [ "$bfile0" = "$bfile" ]; then
        [ -f ${workdir}/$bfile ] || cp $file $workdir
    else
        [ -f ${workdir}/$bfile0 ] || {
            [ "$extension" = "bz2" ] && ( cp $file $workdir ; bunzip2 ${workdir}/$bfile ; ) &
            [ "$extension" = "fz" ] && funpack -O ${workdir}/$bfile0 $file &
            gonogo
        }
    fi
done
wait
for file in `cat $file_list`; do
    bfile=`basename $file`
    bfile0=${bfile%'.bz2'}
    bfile0=${bfile0%'.fz'}
    ls ${workdir}/$bfile0 | awk -F/ '{print $NF}'
done > ${workdir}/$file_list
cd $workdir

file0=`head -1 $file_list`
bin=`gethead SDTBN $file0`
[ "$bin" ] || bin=1
ccd=`gethead CCD_NAME $file0`
[ "$ccd" ] || ccd=`basename $file0 | cut -c16-17`
filter=`gethead FILTER $file0`
[ "$filter" ] || filter=W

ddoti_split.sh $file_list $nsplit

for tag in `ls f??_$file0 | awk -F_ '{print $1}'`; do
    ls ${tag}*.fits > ${tag}_$file_list
    stack.sh ${tag}_$file_list ${tag}_bias.fits &
    gonogo
done
wait

ddoti_unsplit.py bias.fits $nsplit
fpack bias.fits

tag=${ccd}_${filter}_${bin}
cp bias.fits.fz ${bias_archive_dir}/bias_${dte1}_${tag}.fits.fz
cp ${me}_${dte}_$$.log ${bias_archive_dir}/bias_${dte1}_${tag}.log

[ "$cleanup" = "yes" ] && rm -r $workdir
